# config.yaml
device:
  sampling_rate: 5  # Hz
  max_connection_attempts: 5  # Number of connection attempts
  connection_timeout: 10.0    # Seconds to wait for connection
  retry_delay: 5          # Seconds to wait between retries

bluetooth:
  uart_service_uuid: "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
  rx_char_uuid: "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
  tx_char_uuid: "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"

display:
  clear_screen: true