device:
  sampling_rate: 10  # Hz
  max_retry_attempts: 3
  retry_delay: 5.0  # seconds
  packet_size: 80

bluetooth:
  uart_service_uuid: "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"
  rx_char_uuid: "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
  tx_char_uuid: "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"
  desired_mtu: 512
  
display:
  clear_screen: true